config/routes.rb
Rails.application.routes.draw do

  root to: "books#index"

  get '/sign_up' => 'users#new'
  post '/users' => 'users#create'

  get '/sign_in' => 'sessions#new'
  post '/sign_in' => 'sessions#create'
  get 'sign_out' => 'sessions#destroy'

  resources :books
  resources :reviews
  resources :titles
  resources :order_items
  resource :cart, only: [:show]

  get 'finalize' => 'carts#finalize'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :reviews
  has_many :order_items
  belongs_to :title
  validates :name, :title_id ,:author, presence: true
  before_destroy :remove_linked_items

  has_attached_file :cover, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/

  def remove_linked_items
    self.order_items.destroy_all
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  belongs_to :user, optional: true

  def item_total
    order_items.collect { |item| item.quantity }.sum
  end



  def finalize(user)
    self.user_id = user.id
    self.status = 1
    self.save
  end

  def finalized?
    return self.status == 1
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :book
  validates :quantity, numericality: { greater_than_or_equal_to: 1 }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/title.rb
class Title < ApplicationRecord
  has_many :books
  validates :title, presence: true
  before_destroy :remove_linked_items


  def remove_linked_items
    self.books.destroy_all
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :orders
  has_many :reviews

  validates :name, :email, :password, :password_confirmation, presence: true
  validates :name, :email, uniqueness: true

  def previous_orders
    self.orders.where(status: 1).includes(order_items: :book)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  helper_method :admin
  helper_method :current_order

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def admin
    current_user && current_user.admin
  end

  def current_order
    session[:order_id] ? Order.find(session[:order_id]) : Order.new
  end

  def authorize
    redirect_to '/sign_in' unless admin
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authorize, except: [:index, :show]

  def index
    @books = Book.all
    @titles = Title.all
  end

  def show
    @book = Book.find(params[:id])
    @title = Title.find(@book.title_id)
    @order_item = current_order.order_items.new
    @review = @book.reviews.new
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book created!"
      redirect_to '/'
    else
      flash[:alert] = @book.errors.full_messages
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book updated!"
      redirect_to '/'
    else
      flash[:alert] = @book.errors.full_messages
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "Book deleted."
    redirect_to '/'
  end

private
  def book_params
    params.require(:book).permit(:name, :recently_added, :cover, :page_count, :title_id )
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    if current_user
      @previous_orders = current_user.previous_orders
    end
    @order_items = current_order.order_items
  end

  def finalize
    if current_user
      current_order.finalize(current_user)
      session[:order_id] = nil
      redirect_to cart_path
    else
      flash[:alert] = "You need to sign up or sign in to complete your order."
      redirect_to sign_in_path
    end
  end

end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

  def create
    @order = current_order
    @item = @order.order_items.new(item_params)
    if @order.save
      @message = "Item added to Cart!"
      session[:order_id] = @order.id
      flash[:notice] = @message
    else
      @message = @item.errors.full_messages
      flash[:alert] = @message
    end
    redirect_to books_path
  end

  def update
    @order = current_order
    @item = @order.order_items.find(params[:id])
    @item.update_attributes(item_params)
    @order.save
  end

  def destroy
    @order = current_order
    @item = @order.order_items.find(params[:id])
    @item.destroy
    @order.save
    redirect_to cart_path
  end

  private

  def item_params
    params.require(:order_item).permit(:quantity, :book_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    if @review.save
      flash[:notice] = "Reviews added!"
      @book = Book.find(@review.book_id)
      redirect_to book_path(@book)
    else
      flash[:alert] = @review.errors.full_messages
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:review, :user_id, :book_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome back, #{user.name}!"
      redirect_to '/'
    else
      flash[:alert] = user.errors.full_messages
      redirect_to '/sign_in'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've signed out!"
    redirect_to '/sign_in'
  end
end

app/controllers/titles_controller.rb
class TitlesController < ApplicationController

  def show
    @titles = Title.all
    @title = Title.find(params[:id])
    @bookTitle = @title.title
    @books = @title.books
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    user = User.new(user_params)
    if user.name == "admin"
      user.admin = true
    end
    if user.save
      session[:user_id] = user.id
      flash[:notice] = "Welcome, #{user.name}!"
      redirect_to '/'
    else
      flash[:alert] = user.errors.full_messages
      redirect_to '/sign_up'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
  def cart_items
    current_order.item_total
  end
end

app/views/books/_add.html.erb
<div class="home-back">
   <div class="mainwidth">
      <div id="home-images">
         <div class="home-img">
            <a href="#" target="_blank">
            <%= image_tag 'bestSeller.jpg' %>
            </a>
            <div class="stat">
               <h2>Best Sellers</h2>
            </div>
         </div>
         <div class="home-img">
            <div class="hover">
               <a href="" target="_blank">
               <%= image_tag 'classic.jpg' %>
               </a>
            </div>
            <div class="stat">
               <h2>Classics</h2>
            </div>
         </div>
         <div class="home-img">
            <div class="hover">
               <a href="" target="_blank">
               <%= image_tag 'novels.jpg' %>
               </a>
            </div>
            <div class="stat">
               <h2>Amazing Novels</h2>
            </div>
         </div>
      </div>
   </div>
</div>

app/views/books/_allProduct.html.erb
<div class="clear"></div>
<div id="categoryWrapper">
  <div id="navColumnOneWrapper" style="width: 250px">
     <div class="leftBoxContainer" id="categories" style="width: 250px">
        <h3 class="leftBoxHeading" id="categoriesHeading">Categories</h3>
        <div id="cssmenu">
          <ul>
          <% @titles.each do |title| %>
            <li><%= link_to title.title, title_path(title) %></li>
          <% end %>
        </ul>
        </div>
     </div>
</div>
  <div id="productWrapper">
    <h2 class="centerBoxHeading"><%=@bookTitle ? @bookTitle:'Book Lists'%></h2>
    <div class="products">
       <% @books.each do |book| %>
       <div id="book-<%= book.id %>" class="product">
          <div class="centerBoxContentsFeatured centeredContent back" style="width: 33%; height: 371px;">
             <a class="proimage" style="min-height:235px;"><%= image_tag book.cover.url(:medium) %></a>
             <h3>
                <%= link_to book.name, book_path(book), class: 'static-popup-link'%>
              </h3>
          </div>
       </div>
       <% end %>
    </div>
  </div>

<div class="clear"></div>

app/views/books/_form.html.erb
<%= form_for @book do |f| %>
  <div class="input-field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="input-field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="input-field">
    <%= f.label :price %>
    <%= f.number_field :price, step: 0.01 %>
  </div>
  <div class="file-field input-field">
      <div class="btn">
        <span>File</span>
        <%= f.file_field :image %>
      </div>
    </div>
  <%= f.submit "Submit", class: "btn btn-success" %>
<% end %>

app/views/books/_titles.html.erb
<div class="mainwidth">
   <div class="home-img2">
      <a href="#" target="_blank">
      <%= image_tag 'poerty.jpg' %>
      </a>
      <a href="#" class="info">
         <div class="stat2">
            <h2>Poetry</h2>
         </div>
      </a>
   </div>
   <div class="home-img2">
      <a href="#" target="_blank">
      <%= image_tag 'romantic.jpg' %>
      </a>
      <a href="#" class="info">
         <div class="stat2">
            <h2>Romantic</h2>
         </div>
      </a>
   </div>
</div>

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= render "form" %>

app/views/books/index.html.erb
<%= render "add" %>
<%= render "titles" %>
<%= render "allProduct" %>

app/views/books/new.html.erb
<h1>Add a Book</h1>

<%= render "form" %>

app/views/books/show.html.erb
<div class="productDetilsWrapper">
  <div class="productDetils">
    <div class="image-wrapper">
      <%= image_tag @book.cover.url(), class: "responsive-img" %>
    </div>
    <div class="productInfo">
      <h1><%= @book.name %></h1>
      <p><b>Author:</b> <%= @book.author %></p>
      <p><b>Publisher:</b> <%= @book.publisher %></p>
      <p><b>category:</b> <%= @title.title %></p>
      <p><b>Total no of pages:</b> <%= @book.page_count %></p>
      <br>
      <%= form_for @order_item do |f| %>
      <%= f.hidden_field :book_id, value: @book.id %>
        <%= f.hidden_field :quantity, value: 1, class: 'quantity-input' %>
        <%= f.submit "Add to wish list", class: "btn btn-success", id: "add_to_cart" %>
    <% end %>
    </div>
    <div class="clear"></div>
    <h3 class="reviewHeader">Reviews: </h3>
    <%if @book.reviews.length > 1 %>
      <% @book.reviews.each do |reviews| %>
        <% if reviews.review %>
          <div>
            <%= image_tag 'user-dummy.png', class: "user-img" %>
            <%= reviews.user.name %>
          </div>
          <h5 class="reviewDetail"><%= reviews.review %></h5>
        <% end %>
      <% end %>
    <% else %>
      <h5 class="reviewDetail">No reviews are available.</h5>
    <% end %>
    <br>
    <% if current_user %>
      <%= form_for @review do |f| %>
      <%= f.hidden_field :book_id, value: @book.id %>
      <%= f.hidden_field :user_id, value: User.find(session[:user_id]) %>

        <%= f.text_area :review, value: "Good Book!" , size: '100x6' %>
        <br>
        <%= f.submit "Add review", class: "btn btn-success" %>
        <% end %>
    <% end %>
  </div>
</div>

app/views/carts/show.html.erb
<div class="home-back centerWrap">
  <h1>Wish List Books</h1>
  <% if @order_items.any? %>
    <div id="cart-items">
      <%= render "orders/show", order: current_order  %>
      <br>
      <button class="btn btn-info" >
        <%= link_to "Finalize Order", finalize_path %>
      </button>
    </div>
  <% else %>
    <p>Your wish list is empty.</p>
  <% end %>

  <% if current_user && @previous_orders.any? %>
    <div class="divider"></div>
    <h3>Your Order History</h3>
    <% @previous_orders.each do |order| %>
      <div class="section">
        <h4><%= order.updated_at.strftime("%b %-d, %Y") %></h4>
        <%= render "orders/show", order: order  %>
        <h6>Order ID: <%= order.id %></h6>
      </div>
    <% end %>
  <% end %>

</div>

app/views/layouts/_modal.html.erb
<div id="modal-<% object.id %>" class="modal modal-fixed-footer">
  <div class="modal-content">

  </div>
  <div class="modal-footer">
    <%= link_to "Close", books_path,
      class: "modal-action modal-close waves-effect waves-green btn-flat",
      id: "hide-detail-#{ object.id }",
      remote: true %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecommerce</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<body>
  <div class="jumbotron title">
    <div><%= image_tag 'logo.png' %></div>
    <div class="cartWrapper">
      <span class="glyphicon glyphicon-shopping-cart cart cartImg"></span>
      <div class="cart-icon">
        <%= link_to cart_path do %>
        <span class="cart-text">Your wish list contains:</span> <br><span class="count">
         <span class="cart-total"><%= cart_items %></span>
         items</span>
         <% end %>
       </div>
    </div>
  </div>
  <nav class="navbar menu">
    <div class="container-fluid">
    <div class="navbar-header">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home</a></li>
        <li><a href="#">New Arivals</a></li>
        <li><a href="#">NewYork Best Seller</a></li>
        <li><a href="#">Contact Us</a></li>
      </ul>
    </div>
    <ul class="nav navbar-nav right">
      <% if current_user %>
        <% if current_user.admin? %>
          <li><%= link_to "Add a Product", new_product_path %></li>
        <% end %>
        <li><%= link_to "Sign out", '/sign_out' %></li>
      <% else %>
        <li><%= link_to "Sign up", 'sign_up' %></li>
        <li><%= link_to "Sign in", '/sign_in' %></li>
      <% end %>
    </ul>
  </div>
  </nav>

  <body>
    <%= flash[:alert] %>
    <%= flash[:notice] %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/order_items/create.js.erb
$('#order_item_quantity').val(1);
$('.cart-total').text('<%= cart_items %>');

app/views/order_items/destroy.js.erb
$("#order-item-<%= @item.id %>").remove();
$('.cart-total').text("<%= cart_items %>");
$('.cart-price').text("<%= number_to_currency current_order.total_price %>");
<% if cart_items == 0 %>
  $('#cart-with-items').after('<p>Your shopping cart is empty.</p>');
  $('#cart-with-items').remove();
<% end %>

app/views/orders/_show.html.erb
<table class="bordered">
  <thead>
    <tr>
        <th>Book</th>
        <% unless order.finalized? %>
          <th></th>
        <% end %>
    </tr>
  </thead>

  <tbody>
    <% order.order_items.each do |item| %>
      <tr id='order-item-<%= item.id %>'>
        <td><%= item.book.name %></td>
        <% unless order.finalized? %>
          <td><%= link_to "Remove", order_item_path(item), remote: true, :data => {:confirm => "Are you sure you want to remove this item?", :method => "delete"} %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<p>
  Your Issued Date Will Be: <span class="cart-price"><%= Date.today %></span>
  <br>
  Your Return Date Will Be: <span class="cart-price"><%= Date.today + 7.day %></span>
</p>

app/views/titles/show.html.erb
<%= render "books/titles" %>
<%= render "books/allProduct" %>

app/views/users/new.html.erb
<div class="home-back centerWrap">
<h1>Sign up</h1>

<%= form_for :user, url: '/users' do |f| %>
  <div class="input-field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="input-field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div class="input-field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="input-field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit "Sign up", class: "btn btn-success", id: "new_user_button" %>
<% end %>
</div>